TYPE_CREATE_BILL = 0
TYPE_MANAGE_BILL = 1

JSON_ACTION_TYPE = 'at'
JSON_ACTION_ID = 'ai'
JSON_BILL_ID = 'b'
JSON_ITEM_ID = 'i'
JSON_TAX_ID = 't'

EMOJI_MONEY_BAG = '\U0001F4B0'
EMOJI_TAX = '\U0001F4B8'
EMOJI_PERSON = '\U0001F464'
